calendar_ting/urls.py
from django.urls import path

from . import views

app_name = 'calendar_ting'

urlpatterns = [
  path('', views.home, name='home'),
  path('signin/', views.sign_in, name='signin'),
  path('calendar/', views.calendar, name='calendar'),
  path('callback/', views.callback, name='callback'),
  path('signout/', views.sign_out, name='signout'),
  path('calendar/new/', views.newevent, name='newevent'),
  path('calendar/event/<str:eid>', views.event, name='event'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('microsoft/', include('microsoft_auth.urls', namespace='microsoft')),
    # path('', views.HomePage.as_view(), name='home'),
    path('', include('calendar_ting.urls'), name='calendar_ting'),
]

calendar_ting/models.py
from django.db import models

# Create your models here.

calendar_ting/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime, timedelta
from dateutil import tz, parser
from calendar_ting.auth_helper import get_sign_in_flow, get_token_from_code, store_user, remove_user_and_token, get_token
from calendar_ting.graph_helper import *

# Create your views here.
def home(request):

  context = initialize_context(request)
  print(context)
  return render(request, 'calendar_ting/calendar_home.html', context)


def initialize_context(request):
    context = {}

    error = request.session.pop('flash_error', None)

     # Check for any errors in the session
    if error != None:
        context['errors'] = []
        context['errors'].append(error)

    # Check for user in the session
    context['user'] = request.session.get('user', {'is_authenticated': False})
    return context


def sign_in(request):
    # Get the sign-in flow
    flow = get_sign_in_flow()
    # Save the expected flow so we can use it in the callback
    try:
        request.session['auth_flow'] = flow
    except Exception as e:
        print(e)
    # Redirect to the Azure sign-in page
    return HttpResponseRedirect(flow['auth_uri'])


def callback(request):
    # Make the token request
    result = get_token_from_code(request)
    #Get the user's profile
    user = get_user(result['access_token'])
    # Store user
    store_user(request, user)
    return HttpResponseRedirect(reverse('calendar_ting:home'))


def sign_out(request):
  # Clear out the user and token
  remove_user_and_token(request)

  return HttpResponseRedirect(reverse('calendar_ting:home'))


def calendar(request):
    context = initialize_context(request)
    user = context['user']

    # Load the user's time zone
    # Microsoft Graph can return the user's time zone as either
    # a Windows time zone name or an IANA time zone identifier
    # Python datetime requires IANA, so convert Windows to IANA
    time_zone = get_iana_from_windows(user['timeZone'])
    tz_info = tz.gettz(time_zone)

    # Get midnight today in user's time zone
    today = datetime.now(tz_info).replace(
        hour=0,
        minute=0,
        second=0,
        microsecond=0)

    # Based on today, get the start of the week (Sunday)
    if (today.weekday() != 6):
        start = today - timedelta(days=today.isoweekday())
    else:
        start = today

    end = start + timedelta(days=14)

    token = get_token(request)

    events = get_calendar_events(
        token,
        start.isoformat(timespec='seconds'),
        end.isoformat(timespec='seconds'),
        user['timeZone'])

    if events:
        # Convert the ISO 8601 date times to a datetime object
        # This allows the Django template to format the value nicely
        for event in events['value']:
            event['start']['dateTime'] = parser.parse(event['start']['dateTime'])
            event['end']['dateTime'] = parser.parse(event['end']['dateTime'])

        context['events'] = events['value']

    return render(request, 'calendar_ting/calendar.html', context)


def newevent(request):
  context = initialize_context(request)
  user = context['user']

  if request.method == 'POST':
    # Validate the form values
    # Required values
    if (not request.POST['ev-subject']) or \
       (not request.POST['ev-start']) or \
       (not request.POST['ev-end']):
      context['errors'] = [
        { 'message': 'Invalid values', 'debug': 'The subject, start, and end fields are required.'}
      ]
      return render(request, 'calendar_ting/newevent.html', context)

    attendees = None
    if request.POST['ev-attendees']:
      attendees = request.POST['ev-attendees'].split(';')
    body = request.POST['ev-body']

    # Create the event
    token = get_token(request)

    create_event(
      token,
      request.POST['ev-subject'],
      request.POST['ev-start'],
      request.POST['ev-end'],
      attendees,
      request.POST['ev-body'],
      user['timeZone'])

    # Redirect back to calendar view
    return HttpResponseRedirect(reverse('calendar_ting:calendar'))
  else:
    # Render the form
    return render(request, 'calendar_ting/newevent.html', context)
  print('hello')

  
def event(request, eid):
    context = initialize_context(request)
    user = context['user']

    token = get_token(request)

    event = get_event(
        token,
        # "AQMkADAwATM3ZmYAZS1iOTJmLWRjNWItMDACLTAwCgBGAAADHrMG3KU3_0SCPtGAVNpDEgcAWIoDc2XtaEmSPvne0ag-9QAAAgENAAAAWIoDc2XtaEmSPvne0ag-9QAEJvdjKwAAAA=="
        eid
    )

    if event:
        context['event'] = event

    return render(request, 'calendar_ting/event.html', context)

mysite/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'

calendar_ting/templates/calendar_ting/calendar.html
{% extends 'base.html' %}

{% block title %}
  Calendar - Bookalot
{% endblock %}

{% block pagetitle %}
  Calendar
{% endblock %}

{% block pagedescription %}
  Heres your calendar
{% endblock %}

{% block content %}

<a href="{% url 'calendar_ting:newevent' %}" class="btn btn-light btn-sm mb-3">New event</a>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Organizer</th>
      <th scope="col">Subject</th>
      <th scope="col">Start</th>
      <th scope="col">End</th>
      <th scope="col">View</th>
      
    </tr>
  </thead>
  <tbody>
    {% if events %}
      {% for event in events %}
        <tr>
          <td>{{ event.organizer.emailAddress.name }}</td>
          <td>{{ event.subject }}</td>
          <td>{{ event.start.dateTime|date:'n/d/Y g:i A' }}</td>
          <td>{{ event.end.dateTime|date:'n/d/Y g:i A' }}</td>
          <td><a href="{% url 'calendar_ting:event' eid=event.id %}"> View meeting </a> </td>
        </tr>
      {% endfor %}
    {% endif %}
  </tbody>
</table>

{% endblock %}

calendar_ting/templates/calendar_ting/calendar_home.html
{% extends 'base.html' %}

{% block title %}
  Home - Bookalot
{% endblock %}

{% block pagetitle %}
  Welcome to Bookalot
{% endblock %}

{% block pagedescription %}
  Home page
{% endblock %}

{% block content %}

<p>
  Welcome to Hell
</p>

{% endblock %}

calendar_ting/templates/calendar_ting/event.html
{% extends 'base.html' %}

{% block title %}
  Home - Bookalot
{% endblock %}

{% block pagetitle %}
  New event
{% endblock %}

{% block pagedescription %}
  Home page
{% endblock %}

{% block content %}

<p>{{event.start.dateTime}}</p>
<p>{{event.end.dateTime}}</p>
<p>{{event.subject}}</p>
<p>{{event.organizer.emailAddress.name}}</p>
{% for attendee in event.attendees %}
  <p>{{attendee.emailAddress.name}},{{attendee.emailAddress.address}}</p>
{% endfor %}
 <p>{{event.location}}</p>
 <p>{{event}}</p>
 <p>{{user}}</p>

{% endblock %}

calendar_ting/templates/calendar_ting/newevent.html
{% extends 'base.html' %}

{% block title %}
  Home - Bookalot
{% endblock %}

{% block pagetitle %}
  New event
{% endblock %}

{% block pagedescription %}
  Home page
{% endblock %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label>Subject</label>
    <input class="form-control" name="ev-subject" type="text">
  </div>
  <div class="form-group">
    <label>Attendees</label>
    <input class="form-control" name="ev-attendees" type="text"
      placeholder="Separate multiple email addresses with a semicolon (';')">
  </div>
  <div class="form-row">
    <div class="col">
      <div class="form-group">
        <label>Start</label>
        <input class="form-control" name="ev-start" type="datetime-local">
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label>End</label>
        <input class="form-control" name="ev-end" type="datetime-local">
      </div>
    </div>
  </div>
  <div class="form-group mb-3">
    <label>Body</label>
    <textarea class="form-control" name="ev-body" rows="3"></textarea>
  </div>
  <input class="btn btn-primary mr-2" type="submit" value="Create" />
  <a class="btn btn-secondary" href="/calendar">Cancel</a>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

	<title>
		{% block title %}
		{% endblock %}
	</title>

</head>

<body class="d-flex flex-column h-100">
	<header>
		<nav class="navbar p-4 navbar-expand-lg navbar-dark bg-dark" aria-label="Navbar">
			<div class="container">
				<a class="navbar-brand" href="{% url 'calendar_ting:home' %}">Chow website</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#chow-navbar"
					aria-controls="chow-navbar" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="chow-navbar">
					<div class="navbar-nav">
						<!-- Check if current page, maybe move to individual templates -->
						<a class="nav-link" href="{% url 'calendar_ting:home' %}">Home</a>
						<a class="nav-link" href="{% url 'calendar_ting:calendar' %}">Calendar</a>
						<a class="nav-link" href="{% url 'calendar_ting:newevent' %}">Meeting</a>
					</div>
				</div>

				<div class="d-flex align-items-center justify-content-between">
					{% if user.is_authenticated %}
					<span class="navbar-text me-3">Signed in as <span class="fw-bold">{{ user.name }}</span></span>
					<div class="dropdown">
						<a class="dropdown-toggle text-decoration-none link-light" href="" id="chow-dropdown-user"
							data-bs-toggle="dropdown" aria-expanded="false">
							{% if user.avatar %}
							<img src="{{ user.avatar }}"
								class="m-3 rounded-circle" width="32" height="32">
							{% else %}
							<img src="https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg"
								class="m-3 rounded-circle" width="32" height="32">
							{% endif %}
						</a>
						<div class="dropdown-menu dropdown-menu-dark dropdown-menu-end p-3"
							aria-labelledby="chow-dropdown-user">
							{% if user.avatar %}
							<img src="{{ user.avatar }}"
								class="m-3 rounded-circle" width="128" height="128">
							{% else %}
							<img src="https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg"
								class="m-3 rounded-circle" width="128" height="128">
							{% endif %}
							<span class="dropdown-item-text p-3">{{ user.name }}</span>
							<span class="dropdown-item-text p-3">{{ user.email }}</span>
							<hr class="dropdown-divider">
							<a class="p-3 d-flex justify-content-center btn btn-outline-light" href='{% url 'calendar_ting:signout' %}'>Log out</a>
						</div>
					</div>
					{% else %}
					<a href="{% url 'calendar_ting:signin' %}" class="btn btn-primary me-2">Sign In</a>
					{% endif %}
				</div>
			</div>
		</nav>
	</header>

	<main>
		<!-- template stuff -->
		<div class="container">
			<h1 class="mt-5">
				{% block pagetitle %}
				{% endblock %}
			</h1>
			<p class="lead mb-5">
				{% block pagedescription %}
				{% endblock %}
			</p>
			<div>
				{% block content %}
				{% endblock %}
				
			</div>
		</div>
		<hr class="mt-5 mb-5 featurette-divider">
	</main>
	<footer class="mt-auto py-3">
		<div class="container">
			<p class="text-muted">Jeff Chow @ 2021</p>
		</div>
	</footer>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
		crossorigin="anonymous"></script>
</body>

</html>

templates/base2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  {% load static %}
	<meta charset="utf-8">
	<title>pls</title>

	<!-- fabric core -->
	<link rel="stylesheet"
		href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css" />

	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

	<!-- Google font stylesheet -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="{% static "mysite/css/master.css" %}">
	<link rel="stylesheet" href="{% static "css/master.css" %}">
	<link rel="stylesheet" href="{% static "calendar_ting/css/app.css" %}">

</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<a class="navbar-brand mynav" href="{% url 'home' %}">Calender Ting</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
				aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				<ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link {% if request.resolver_match.view_name == 'home' %} active{% endif %}"
      						href="{% url 'calendar_ting:home' %}">Home</a></li>
					{% if user.is_authenticated %}

					<li class="nav-item">
						<a class="nav-link avatar-link" href="#"
							aria-haspopup="true" aria-expanded="false">
							{% if user.avatar %}
							<img src="{{ user.avatar }}" class="rounded-circle align-self-center mr-2"
								style="width: 32px;">
							{% else %}
							<img src="{% static 'calendar_ting/images/no-profile-photo.png' %}"
								class="rounded-circle align-self-center mr-2" style="width: 32px;">
							{% endif %}
            </a>
							<div>
								<h5 class="dropdown-item-text mb-0">{{ user.name }}</h5>
								<p class="dropdown-item-text text-muted mb-0">{{ user.email }}</p>
								<div class="dropdown-divider"></div>
								<a href="{% url 'calendar_ting:signout' %}" class="dropdown-item">Logout</a>
							</div>
					</li>
					{% else %}
					<a class="nav-link" href="{% url 'calendar_ting:signin' %}">Login</a>
					{% endif %}
          </ul>
				</div>
			</div>
	</nav>
	<div class="container mycontent">
		{% block content %}

		{% endblock %}
	</div>



	<script type="text/javascript" src="{% static 'mysite/js/master.js' %}"></script>

	<!-- Bootstrapj js -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
		crossorigin="anonymous"></script>

	<!-- Latest compiled and minified jQuery -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"
		integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</body>


</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
  Home - Bookalot
{% endblock %}

{% block pagetitle %}
  Welcome to Bookalot
{% endblock %}

{% block pagedescription %}
  Home page
{% endblock %}

{% block content %}

<p>
  Welcome to Hell
</p>

{% endblock %}